# see https://github.com/marketplace/actions/license-eye-header#configurations

header:
  license:
    spdx-id: Apache-2.0
    copyright-year: 2026
    copyright-owner: Zaphiro Technologies

  paths-ignore:
    - ".github/config"
    - "**/*.{md,MD}"
    - "LICENSE"
    - "NOTICE"
    - ".*"
    - ".vscode/**"
    - "vendor/**"

  comment: on-failure
