matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .github/config/wordlist.txt # <-- put path to custom dictionary file here
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
