name: Validate PR

concurrency:
  group: ${{ github.ref_name }}-validate-pr
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled
  workflow_call:
    inputs:
      labels:
        description: 'Labels to be checked'
        default: 'feature,bug,ci,refactor,security,documentation,dependencies,skip-changelog'
        required: false
        type: string
jobs:
  # pr-title-lint:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     statuses: write
  #   steps:
  #     # see https://www.conventionalcommits.org/en/v1.0.0/
  #     - uses: aslafy-z/conventional-pr-title-action@v3
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          github_enterprise_graphql_url: https://api.github.com/graphql
          one_of: ${{ github.event_name == 'workflow_call' && inputs.labels || 'feature,bug,ci,refactor,security,documentation,dependencies,skip-changelog' }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
