# Copyright 2024 Zaphiro Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Validate PR

concurrency:
  group: ${{ github.ref_name }}-validate-pr
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled
  workflow_call:
    inputs:
      labels:
        description: 'Labels to be checked'
        default: 'feature,bug,ci,refactor,security,documentation,dependencies,skip-changelog'
        required: false
        type: string
jobs:
  # pr-title-lint:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     statuses: write
  #   steps:
  #     # see https://www.conventionalcommits.org/en/v1.0.0/
  #     - uses: aslafy-z/conventional-pr-title-action@v3
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          github_enterprise_graphql_url: https://api.github.com/graphql
          one_of: ${{ inputs.labels !='' && inputs.labels || 'feature,bug,ci,refactor,security,documentation,dependencies,skip-changelog' }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
