# Copyright 2024 Zaphiro Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Golang Lint & Test

concurrency:
  group: ${{github.repository}}-${{ github.ref_name }}-go
  cancel-in-progress: true

# Permissions needed
# permissions:
#   # Give the default GITHUB_TOKEN write permission to commit and push the
#   # updated CHANGELOG back to the repository.
#   # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
#   contents: write

on:
  workflow_call:
    inputs:
      alert-threshold-benchmark:
        required: false
        default: 150%
        type: string
        description: Percent that will trigger benchmark alert
      skip-benchmark:
        required: false
        default: false
        type: boolean
        description: True to skip benchmark exec
      skip-sbom:
        required: false
        default: false
        type: boolean
        description: True to skip sbom exec
      config-sbom-path:
        default: '.github/config/syft.yaml'
        required: false
        type: string
      
jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    env:
      GOPRIVATE: github.com/zaphiro-technologies/*
      GH_ACCESS_TOKEN: ${{ secrets.REPO_PRIVATE_READ_PAT }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}} # Can't commit on detached PR merge commit, so this checkouts the branch
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Golines
        run: |
          go install github.com/segmentio/golines@latest
          golines . -w
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --fix
          version: latest
      - name: Commit golines & golangci-lint changes
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@zaphiro.ch'
          git commit -am "Automated lint fixes" || echo "No changes to commit"
          git push
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/zaphiro-technologies/*
      GH_ACCESS_TOKEN: ${{ secrets.REPO_PRIVATE_READ_PAT }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install gcov2lcov
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
      # We Login in GHCR to retrieve owned private images used in docker-compose
      # This requires to set in the package settings read permission for the
      # repository where the golang ci is running
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          make ci-test
      - name: Download code coverage report from base branch
        uses: dawidd6/action-download-artifact@v3
        if: github.actor != 'dependabot[bot]'
        with:
          name: cov-result
          github_token: ${{ secrets.REPO_PRIVATE_READ_PAT }}
          branch: ${{github.base_ref}}
          if_no_artifact_found: warn
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        if: github.actor != 'dependabot[bot]'
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: ${{ hashFiles('./lcov.info') != ''  && './lcov.info' || null }}
          minimum-ratio: 70
          send-summary-comment: true
          show-annotations: ""
      - name: Upload code coverage for ref branch
        if: ${{ ! github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: cov-result
          path: ./coverage/lcov.info
          retention-days: 400
      
  benchmark:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.skip-benchmark}}
    env:
      GOPRIVATE: github.com/zaphiro-technologies/*
      GH_ACCESS_TOKEN: ${{ secrets.REPO_PRIVATE_READ_PAT }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      # We Login in GHCR to retrieve owned private images used in docker-compose
      # This requires to set in the package settings read permission for the
      # repository where the golang ci is running
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run benchmark
        shell: bash
        run: make ci-bench | tee output.txt
      # Download previous benchmark result from cache (if exists)
      - name: Download benchmark report from base branch
        uses: dawidd6/action-download-artifact@v3
        with:
          name: benchmark-result
          github_token: ${{ secrets.REPO_PRIVATE_READ_PAT }}
          branch: ${{ github.base_ref || github.ref_name }}
          if_no_artifact_found: warn
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: "go"
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # Where the previous data file is stored
          external-data-json-path: benchmark-data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # Enable alert commit comment
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: ${{ inputs.alert-threshold-benchmark }}
          summary-always: true
      - name: Upload code coverage for ref branch
        if: ${{ ! github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-result
          path: benchmark-data.json
          retention-days: 400
  sbom:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.skip-sbom }}
    env:
      GOPRIVATE: github.com/zaphiro-technologies/*
      GH_ACCESS_TOKEN: ${{ secrets.REPO_PRIVATE_READ_PAT }}
    steps:
      - uses: actions/checkout@v4
      #- run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      #- name: Set up Go
      #  uses: actions/setup-go@v5
      #  with:
      #    go-version-file: go.mod
      #- name: Build
      #  run: go build -v ./...
      - name: sbom
        if: ${{ ! inputs.skip-sbom }}
        uses: anchore/sbom-action@v0
        with:
          config: ${{ inputs.config-sbom-path || '.github/config/syft.yaml' }}
