# Copyright 2024 Zaphiro Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
      - "*"
  pull_request_review:
  pull_request:
    types:
      - labeled
      - unlabeled
      - edited
      - synchronize
    branches:
      - main
  release:
    types:
      - published
  workflow_call:
    inputs:
      config-release-path:
        required: false
        default: ".github/config/release-config.json"
        type: string
      skip-sbom:
        required: false
        default: false
        type: boolean
        description: True to skip sbom exec

concurrency:
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  check_reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - name: PR approval check
        if: ${{ github.event_name == 'pull_request' }}
        id: reviews
        env:
          pr: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          state=$(gh pr view "$pr" \
              --repo "$GITHUB_REPOSITORY" \
              --json reviewDecision \
              --jq '.reviewDecision')
          echo "state=$state" >> "$GITHUB_OUTPUT"
  release_notes:
    needs: check_reviews
    name: Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    if: ${{ ((github.event_name == 'pull_request' && needs.check_reviews.outputs.reviews == 'APPROVED') || github.event.review.state == 'approved' || startsWith(github.ref, 'refs/tags/')) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && (github.event_name != 'pull_request_review' || github.event.pull_request.head.repo.full_name == github.repository) }}
    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
      - uses: actions/checkout@v6
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - uses: actions/checkout@v6
        if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
        with:
          ref: ${{ github.ref }}
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - name: "Get Previous tag"
        id: previoustag
        shell: bash
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      - name: "Get next minor version"
        id: semvers
        shell: bash
        run: |
          PREV="${{ steps.previoustag.outputs.tag }}"
          VERSION="${PREV#v}"

          if [[ "$VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
          else
            MAJOR=0
            MINOR=0
            PATCH=0
          fi

          NEXT_PATCH="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "patch=$NEXT_PATCH" >> "$GITHUB_OUTPUT"
      - name: Select configuration
        if: ${{ github.event_name == 'workflow_call' }}
        run: echo "CONFIGURATION=${{ inputs.config-release-path }}" >> $GITHUB_ENV
      - name: Select configuration
        if: ${{ github.event_name != 'workflow_call' }}
        run: echo "CONFIGURATION='.github/config/release-config.json'" >> $GITHUB_ENV
      - name: Get Pull Request Number
        if: ${{ github.event.review.state == 'approved' }}
        run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash
      - name: "Update changelog config"
        id: update_changelog_config
        env:
          PR: ${{ github.event.review.state == 'approved' && env.PULL_NUMBER || github.event.number }}
        run: |
          jq --arg match "myPR" \
            --arg replace "$PR" \
            'walk(if . == $match then $replace else . end)' < ${{ env.CONFIGURATION }} > .github/config/release-config-temp.json
          more .github/config/release-config-temp.json
      - name: "Build Changelog"
        id: build_changelog_1
        uses: mikepenz/release-changelog-builder-action@v6
        if: ${{ steps.previoustag.outputs.tag != '0.0.0' }}
        with:
          configuration: ".github/config/release-config-temp.json"
          failOnError: true
          includeOpen: true
          fromTag: ${{ steps.previoustag.outputs.tag }}
          toTag: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build Changelog"
        id: build_changelog_2
        uses: mikepenz/release-changelog-builder-action@v6
        if: ${{ steps.previoustag.outputs.tag == '0.0.0' }}
        with:
          configuration: ".github/config/release-config-temp.json"
          failOnError: true
          includeOpen: true
          toTag: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean log
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        run: |
          if [ -f "RELEASE_NOTES.md" ]; then
            # more RELEASE_NOTES.md
            line_start=$(grep -m1 -n "## ${{ steps.semvers.outputs.patch }}" RELEASE_NOTES.md | head -n1 |sed 's/:.*//')
            export line_start
            line_end=$(grep -m2 -n "^## " RELEASE_NOTES.md | head -2 | tail -1 | sed 's/:.*//')
            if [[ $line_end -eq $line_start ]] || [[ -z "${line_end}" ]]; then    line_end=$(wc -l < RELEASE_NOTES.md); else line_end=$(echo $line_end-1 | bc); fi
            export line_end
            PATTERN=${line_start},${line_end}d
            export PATTERN
            # echo $PATTERN
            if [[ -z "${line_start}" ]]; then echo "Empty"; else sed -i -e $PATTERN RELEASE_NOTES.md; fi
            echo "cleaned release note:"
            more RELEASE_NOTES.md
            rm .github/config/release-config-temp.json
          else
            echo -en "# ${GITHUB_REPOSITORY#*/} Release Notes\n" > RELEASE_NOTES.md
          fi
      - name: Clean log
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          if [ -f "RELEASE_NOTES.md" ]; then
            more RELEASE_NOTES.md
            TAG=${{ steps.previoustag.outputs.tag }}
            NEW_VERSION=${TAG#v}
            echo "NEW_VERSION=$NEW_VERSION"
            sed -i.bak -E "s/^(##[[:space:]]+)[0-9]+\.[0-9]+\.[0-9]+-dev/\1${NEW_VERSION}/" RELEASE_NOTES.md
            rm -f RELEASE_NOTES.md.bak
            echo "cleaned release note:"
            more RELEASE_NOTES.md
            rm .github/config/release-config-temp.json
          else
            echo -en "# ${GITHUB_REPOSITORY#*/} Release Notes\n" > RELEASE_NOTES.md
          fi
      - name: Update Changelog (tag)
        uses: stefanzweifel/changelog-updater-action@v1
        if: ${{ steps.previoustag.outputs.tag != '0.0.0' }}
        with:
          latest-version: ${{ steps.semvers.outputs.patch }}-dev
          release-notes: ${{ steps.build_changelog_1.outputs.changelog }}
          path-to-changelog: RELEASE_NOTES.md
      - name: Update Changelog (no tag)
        uses: stefanzweifel/changelog-updater-action@v1
        if: ${{ steps.previoustag.outputs.tag == '0.0.0' }}
        with:
          latest-version: ${{ steps.semvers.outputs.patch }}-dev
          release-notes: ${{ steps.build_changelog_2.outputs.changelog }}
          path-to-changelog: RELEASE_NOTES.md
      - name: Prettify RELEASE_NOTES.md
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --prose-wrap always --write RELEASE_NOTES.md
          dry: true
          no_commit: true
      - name: Commit updated CHANGELOG
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{github.event.pull_request.head.ref}}
          commit_message: "docs(release_notes): update RELEASE_NOTES.md [dependabot skip]"
          file_pattern: RELEASE_NOTES.md
      - name: Commit updated CHANGELOG
        if: startsWith(github.ref, 'refs/tags/')
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: "docs(release_notes): update RELEASE_NOTES.md"
          file_pattern: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ ! inputs.skip-sbom || inputs.skip-sbom == '' }}
        name: Generate SBOM
        # trivy-action v0.35.0 (safe version)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: fs
          scan-ref: "."
          format: "cyclonedx"
          output: "cyclonedx-sbom.json"
      - if: ${{ ! inputs.skip-sbom || inputs.skip-sbom == '' }}
        name: Upload SBOM as a Github artifact
        uses: actions/upload-artifact@v7
        with:
          name: trivy-sbom-report
          path: "${{ github.workspace }}/cyclonedx-sbom.json"
          retention-days: 20 # 90 is the default

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Select configuration
        if: ${{ github.event_name == 'workflow_call' }}
        run: echo "CONFIGURATION=${{ inputs.config-release-path }}" >> $GITHUB_ENV
      - name: Select configuration
        if: ${{ github.event_name != 'workflow_call' }}
        run: echo "CONFIGURATION=.github/config/release-config.json" >> $GITHUB_ENV
      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          configuration: ${{env.CONFIGURATION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-sbom:
    name: Release SBOM
    if: ${{ github.event_name == 'release' && (! inputs.skip-sbom || inputs.skip-sbom == '') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate SBOM
        # trivy-action v0.35.0 (safe version)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: fs
          scan-ref: "."
          format: "cyclonedx"
          output: "cyclonedx-sbom.json"
      - name: Attach SBOM to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" cyclonedx-sbom.json --repo "$GITHUB_REPOSITORY" --clobber
